apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-sql.fullname" . }}-collector
  labels:
    app.kubernetes.io/name: {{ include "prometheus-sql.name" . }}
    helm.sh/chart: {{ include "prometheus-sql.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
{{- $root := . -}}
{{- range $key, $value := .Values.collectorFiles }}
  {{ $key }}: |
{{ toYaml $value | default "{}" | indent 4 }}
{{- end -}}


