apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-sql.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "prometheus-sql.name" . }}
    helm.sh/chart: {{ include "prometheus-sql.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prometheus-sql.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "prometheus-sql.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['sh', '-c', 'sql_exporter -config.file /tmp/sql_exporter.yml -logtostderr']
          volumeMounts:
          - name: config
            mountPath: /tmp
          - name: collector-volume
            mountPath: /tmp/collector
            readOnly: true
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: config
        configMap:
          name: {{ include "prometheus-sql.fullname" . }}
          mountPath: /tmp/sql_exporter.yml
          subPath: sql_exporter.yml
      - name: collector-volume
        configMap:
          name: {{ include "prometheus-sql.fullname" . }}-collector


      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
